protocol: "ICM2O"
train_set: ["Replay", "CASIA_faceAntisp", "MSU-MFSD"]
test_set: ["OULU-NPU"]

running_name: ""

PATH:
    data_folder: "/mnt/e/fas/datasets/"
    output_folder: "/mnt/e/fas/GAC-FAS/"

SYS:
    num_gpus: 1
    GPUs: "0"
    num_workers: 4
    precision: "32"
    matmul_precision: "high"
MODEL:
    model_name: "resnet18"
    norm: True
    usebias: False
    image_size: 256
    num_classes: 1

TRAIN:
    pretrained: "imagenet"
    batch_size: 96
    lr: 0.005
    fc_lr_scale: 10
    weight_decay: 0.0001
    momentum: 0.9
    lr_step_size: 40
    lr_gamma: 0.5
    optimizer: "SGD"
    scheduler: "step"
    warming_epochs: 1
    epochs: 150
    loss_func: "bce"
    logit_scale: 12
    rotate: True
    cutout: True
    feat_loss: "supcon"
    lambda_constrast: 0.2

    minimizer: "gac-fas"
    minimizer_warming: 10

    GAC-FAS:
        rho: 0.1
        eta: 0.0
        alpha: 0.0002
TEST:
    eval_preq: 5
